- name: configuring expense app backend
  hosts: backend
  become: true
  tasks:
    - name: set hostname
      ansible.builtin.shell: set-hostname backend 

    - name: disable nodejs disable module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Installing nodejs server as backend
      ansible.builtin.package:
        name: nodejs
        state: present
        

    - name: create local user account
      ansible.builtin.user:
        name: expense

    - name: create directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download file with checksum url (sha256)
      ansible.builtin.get_url:
        url: https://expense-web-app.s3.amazonaws.com/backend.zip
        dest: /tmp/backend.zip

    - name: Unarchive
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json using the npm installed with nvm v0.10.1.
      community.general.npm:
       path: /app
       state: present

      
    - name: copy
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
       path: /app
       state: directory
       recurse: yes
       owner: expense
       group: expense
       mode: '0775'

    - name: install mysql server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: Installing pre-req package for schema injection
      ansible.builtin.pip:
        name: 
         - pymysql
         - cryptography
        executable: pip3.11

    - name: Schema Injection
      community.mysql.mysql_db:
        name: all
        state: import
        target: /app/schema/backend.sql 
        login_host: 172.31.45.133
        login_user: root
        login_password: ExpenseApp@1
    
    - name: Restart service 
      ansible.builtin.systemd_service:
       state: restarted
       daemon_reload: true
       name: backend
