- name: configuring frontend app
  hosts: all
  become: true
  tasks:

   - name: Installing nginx server as front end
     ansible.builtin.dnf:
      name: nginx
      state: present

   - name: Start service nginx
     ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

   - name: Recursively remove directory
     ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

   - name: Git checkout
     ansible.builtin.git:
      repo: 'https://expense-web-app.s3.amazonaws.com/frontend.zip'
      dest: /tmp/frontend.zip

   - name: create directory
     ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

   - name: Unarchive
     ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

   - name: copy
     ansible.builtin.copy:
      src: expense.conf
      dest: etc/nginx/default.d/expense.conf

   - name: Start service nginx
     ansible.builtin.service:
      name: nginx
      state: restarted
     
      
      

    