- name: install
  hosts: mysql
  become: true
  tasks:
  - name: install mysql server
    ansible.builtin.yum:
      name: mysql-server
      state: present
    
  - name:  service restart
    ansible.builtin.service:
       name: mysqld
       state: started

  - name: setting mysql root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

   